CREATE DATABASE fundraising;
\c fundraising
CREATE TABLE IF NOT EXISTS items (
	id				SERIAL PRIMARY KEY,
	upc				varchar(50) NOT NULL,
	name			varchar(50) NOT NULL,
	cost			money,
	retail_price	money NOT NULL
);

CREATE TABLE IF NOT EXISTS scans (
	item_id			int NOT NULL,
	time			timestamp with time zone NOT NULL,
	purchase		boolean,
	quantity		int
);

CREATE TABLE IF NOT EXISTS inventory (
	item_id			int NOT NULL,
	amount			int,
	sold			int
);