CREATE DATABASE fundraising;
\c fundraising
CREATE TABLE IF NOT EXISTS items (
	upc				varchar(50) PRIMARY KEY,
	name			varchar(50) NOT NULL,
	cost			money,
	retail_price	money NOT NULL
);

CREATE TABLE IF NOT EXISTS scans (
	item_upc		varchar(50),
	time			timestamp with time zone,
	purchase		boolean,
	quantity		int
);

CREATE TABLE IF NOT EXISTS inventory (
	item_upc		varchar(50),
	amount			int,
	sold			int
);